#!/usr/bin/env python3
import sys
import time
import json
import requests
import urllib3
from urllib3.exceptions import InsecureRequestWarning
urllib3.disable_warnings(InsecureRequestWarning)

IP = '10.45.140.160'
USER = 'admin'
PASSWORD = 'Nutanix.123'

# (1) Make Session
session = requests.Session()
session.auth = (USER, PASSWORD)
session.verify = False
session.headers.update({'Content-Type': 'application/json; charset=utf-8'})

# (2) Make URL
NTXPRISMCENTRAL = '10.45.140.160:9440'
NTXBASEURL3 = 'https://10.45.140.160:9440/api/nutanix/v3/idempotence_identifiers'
NTXBASEURL2 = 'https://{prismhost}/PrismGateway/services/rest/{version}/vms'.format(prismhost=NTXPRISMCENTRAL, version='v2.0')
	
def getSingleVMSnapDetails(testVMSnap_UUID):
	getVMsnaps = 'https://{prismhost}/api/nutanix/v3/vm_snapshots/{uuid}'.format(prismhost = NTXPRISMCENTRAL, uuid = testVMSnap_UUID)
	getVMsnaps_response = session.get(getVMsnaps)
	print(getVMsnaps_response.text)
	z = json.loads(getVMsnaps_response.text)
	if getVMsnaps_response.ok:
		print(json.dumps(getVMsnaps_response.json(), indent = 2))
		#print(z['entities'][0]['vm_uuid'])
	else:
		print('ERROR: Could not get VM Snapshots')


def main():
	#print("IN MAIN")
	parameter_name_1 = sys.argv[1]
	getSingleVMSnapDetails(parameter_name_1)

if __name__ == "__main__":
	main()