#!/usr/bin/env python3
import sys
import time
import json
import requests
import urllib3
from urllib3.exceptions import InsecureRequestWarning
urllib3.disable_warnings(InsecureRequestWarning)

IP = '10.45.140.160'
USER = 'admin'
PASSWORD = 'Nutanix.123'

# (1) Make Session
session = requests.Session()
session.auth = (USER, PASSWORD)
session.verify = False
session.headers.update({'Content-Type': 'application/json; charset=utf-8'})

# (2) Make URL
NTXPRISMCENTRAL = '10.45.140.160:9440'
NTXBASEURL3 = 'https://10.45.140.160:9440/api/nutanix/v3/idempotence_identifiers'
NTXBASEURL2 = 'https://{prismhost}/PrismGateway/services/rest/{version}/vms'.format(prismhost=NTXPRISMCENTRAL, version='v2.0')

def listAllVMSnaps(VM_UUID):
	urlrun = 'https://{prismhost}/api/nutanix/{version}/vm_snapshots/list'.format(prismhost=NTXPRISMCENTRAL, version='v3')

	data = {
        "filter": 'entity_uuid==' + VM_UUID,
        "kind": "vm_snapshot"
	}

	listVMSnapsID_response = session.post(urlrun, data=json.dumps(data))
	if listVMSnapsID_response.ok:
		listVMSnapsID_details = listVMSnapsID_response.json()
            # return the unique element
		print(json.dumps(listVMSnapsID_details, indent = 2))
	else:
		print("ERROR: VM Snaps could not be listed")

def main():
	print("Usage:  ./listAllVMSnaps <VM_UUID>: \n")
	parameter_name_1 = sys.argv[1]
	listAllVMSnaps(parameter_name_1)

if __name__ == "__main__":
	main()